{
    "IDEB - Anos Iniciais": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g17.1--g17.2--g17.3--g17.4--t17.1--t17.2.py\", line 137, in <module>\n    data = c.open_file(dbs_path, os.listdir(dbs_path)[0], ext='zip', excel_name='divulgacao', skiprows=9)\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 124, in open_file\n    with zipfile.ZipFile(os.path.join(dir_path, file_path), 'r') as zfile:\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\zipfile.py\", line 1269, in __init__\n    self._RealGetContents()\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\zipfile.py\", line 1336, in _RealGetContents\n    raise BadZipFile(\"File is not a zip file\")\nzipfile.BadZipFile: File is not a zip file\n",
    "IDEB Resultados": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g17.1--g17.2--g17.3--g17.4--t17.1--t17.2.py\", line 173, in <module>\n    data = c.open_file(dbs_path, os.listdir(dbs_path)[0], ext='zip', excel_name='divulgacao', skiprows=9)\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 124, in open_file\n    with zipfile.ZipFile(os.path.join(dir_path, file_path), 'r') as zfile:\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\zipfile.py\", line 1269, in __init__\n    self._RealGetContents()\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\zipfile.py\", line 1336, in _RealGetContents\n    raise BadZipFile(\"File is not a zip file\")\nzipfile.BadZipFile: File is not a zip file\n",
    "Gráfico 17.3": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g17.1--g17.2--g17.3--g17.4--t17.1--t17.2.py\", line 263, in <module>\n    data = c.open_file(dbs_path, 'ideb_resultados.xlsx', 'xls', sheet_name='Sheet1').query(\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 106, in open_file\n    dataframe = pd.read_excel(os.path.join(dir_path, file_path),\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 495, in read_excel\n    io = ExcelFile(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1550, in __init__\n    ext = inspect_excel_format(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1402, in inspect_excel_format\n    with get_handle(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\common.py\", line 882, in get_handle\n    handle = open(handle, ioargs.mode)\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\tmptxe43glm\\\\ideb_resultados.xlsx'\n",
    "Gráfico 17.4": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g17.1--g17.2--g17.3--g17.4--t17.1--t17.2.py\", line 284, in <module>\n    data = c.open_file(dbs_path, 'ideb_resultados.xlsx', 'xls', sheet_name='Sheet1').query(\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 106, in open_file\n    dataframe = pd.read_excel(os.path.join(dir_path, file_path),\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 495, in read_excel\n    io = ExcelFile(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1550, in __init__\n    ext = inspect_excel_format(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1402, in inspect_excel_format\n    with get_handle(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\common.py\", line 882, in get_handle\n    handle = open(handle, ioargs.mode)\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\tmptxe43glm\\\\ideb_resultados.xlsx'\n",
    "Tabela 17.2": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g17.1--g17.2--g17.3--g17.4--t17.1--t17.2.py\", line 305, in <module>\n    data = c.open_file(dbs_path, 'ideb_resultados.xlsx', 'xls', sheet_name='Sheet1').query('`Região` == \"Sergipe\"')\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 106, in open_file\n    dataframe = pd.read_excel(os.path.join(dir_path, file_path),\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 495, in read_excel\n    io = ExcelFile(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1550, in __init__\n    ext = inspect_excel_format(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\excel\\_base.py\", line 1402, in inspect_excel_format\n    with get_handle(\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\site-packages\\pandas\\io\\common.py\", line 882, in get_handle\n    handle = open(handle, ioargs.mode)\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\tmptxe43glm\\\\ideb_resultados.xlsx'\n"
}